admin-adv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('customers/', include('apps.customers.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path('attendances/', include('apps.attendances.urls')),
]

apps/attendances/urls.py
from django.urls import path
from apps.attendances import views

app_name = 'attendances'

urlpatterns = [
    path('list/', views.AttendanceList.as_view(), name='list'),
    path('create/', views.AttendanceCreate.as_view(), name='create'),
]

apps/attendances/models.py
from django.db import models
import datetime


class Attendance(models.Model):
    date = models.DateField('Data')
    horary = models.TimeField('Horário')
    topic = models.CharField('Assunto', max_length=300)
    attended = models.CharField('Atendido', max_length=150)

    class Meta:
        verbose_name = 'Atendimento'
        verbose_name_plural = 'Atendimentos'

    @property
    def is_today(self):
        if self.date == datetime.date.today():
            return True

    def __str__(self):
        return str(self.date)

apps/attendances/forms.py
from django.forms.models import ModelForm

# models
from apps.attendances.models import Attendance


class AttendanceCreate(ModelForm):
    class Meta:
        model = Attendance
        fields = ['date', 'horary', 'topic', 'attended', ]


class AttendanceUpdate(ModelForm):
    class Meta:
        model = Attendance
        fields = ['date', 'horary', ]

apps/attendances/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
# models
from apps.attendances.models import Attendance

# forms
from apps.attendances.forms import AttendanceCreate


class AttendanceList(LoginRequiredMixin, ListView):
    template_name = 'attendance/attendance_list.html'
    model = Attendance
    paginate_by = 50
    context_object_name = 'attendances'


class AttendanceCreate(LoginRequiredMixin, CreateView):
    template_name = 'attendance/attendance_create.html'
    model = Attendance
    form_class = AttendanceCreate
    success_url = reverse_lazy('attendances:list')

apps/attendances/templates/attendance/attendance_create.html
{% extends 'theme/layouts/base.html' %}

{% load widget_tweaks %}

{% block page_title %} Novo Agendamento {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <form method="post">
            {% csrf_token %}
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-sm-2">
                            <label for="{{ form.date.auto_id }}">
                                {{ form.date.label }}:
                            </label>
                            {% render_field form.date class="form-control" type="date" %}
                        </div>
                        <div class="form-group col-sm-1">
                            <label for="{{ form.horary.auto_id }}">
                                {{ form.horary.label }}
                            </label>
                            {% render_field form.horary class="form-control" type="time" placeholder="qdbkqdbqw" %}
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="{{ form.topic.auto_id }}">
                                {{ form.topic.label }}
                            </label>
                            {% render_field form.topic class="form-control" %}
                        </div>
                        <div class="form-group col-sm-5">
                            <label for="{{ form.attended.auto_id }}">
                                {{ form.attended.label }}
                            </label>
                            {% render_field form.attended class="form-control" %}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-success float-right">
                        <i class="fas fa-check mr-2"></i>Salvar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

apps/attendances/templates/attendance/attendance_list.html
{% extends 'theme/layouts/base.html' %}

{% block page_title %} Agenda {% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm-12">
                <a href="{% url 'attendances:create' %}" class="btn btn-success float-right">
                    <i class="fas fa-plus mr-2"></i>Novo Agendamento
                </a>
            </div>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Data</th>
                <th>Hora</th>
                <th>Atendido</th>
                <th>Assunto</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            {% for attendance in attendances %}
            <tr>
                <td>{{ attendance.pk }}</td>
                {% if attendance.is_today %}
                <td>
                    {{ attendance.date }} <span class="badge badge-success ml-2">Hoje</span>
                </td>
                {% else %}
                <td>{{ attendance.date }}</td>
                {% endif %}
                <td>{{ attendance.horary }}</td>
                <td>{{ attendance.attended }}</td>
                <td>{{ attendance.topic }}</td>
                <td>--- ---</td>
                <td class="text-center">
                    <a href="#" title="Concluir" class="btn btn-success btn-sm py-2">
                        <i class="fas fa-check-circle"></i>
                    </a>
                    <a href="#" title="Remarcar" class="btn btn-primary btn-sm py-2">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="#" title="Cancelar" class="btn btn-danger btn-sm py-2">
                        <i class="fas fa-window-close"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <td colspan="6" class="text-center">Nenhum atendimento agendado</td>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->
</div>
{% endblock %}