admin-adv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('customers/', include('apps.customers.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path('attendances/', include('apps.attendances.urls')),
]

apps/accounts/urls.py
from django.urls import path
from apps.accounts import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

apps/attendances/urls.py
from django.urls import path
from apps.attendances import views

app_name = 'attendances'

urlpatterns = [
    path('list/', views.AttendanceList.as_view(), name='list'),
    path('create/', views.AttendanceCreate.as_view(), name='create'),
]

apps/contacts/urls.py
from django.urls import path
from apps.contacts import views

app_name = 'contacts'

urlpatterns = [
    path('contact-list/', views.ContactList.as_view(), name='contact_list'),
]

apps/customers/urls.py
from django.urls import path
from apps.customers import views

app_name = 'customers'

urlpatterns = [
    path('customers-list/', views.CustomersList.as_view(), name='customers_list'),
    path('customers-create/', views.CustomerCreate.as_view(), name='customers_create'),
    path('customers-detail/<int:pk>', views.CustomerDetail.as_view(), name='customers_detail'),
    path('customers-update/<int:pk>', views.CustomerUpdate.as_view(), name='customers_update'),
]

apps/theme/models.py
from django.db import models

# Create your models here.

apps/theme/forms.py
from django.forms.models import ModelForm

theme/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'theme/layouts/base.html'

apps/theme/templates/theme/partials/footer.html
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.4
    </div>
  </footer>

apps/theme/templates/theme/partials/navbar.html
 <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Início</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
<!--    <form class="form-inline ml-3">-->
<!--      <div class="input-group input-group-sm">-->
<!--        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">-->
<!--        <div class="input-group-append">-->
<!--          <button class="btn btn-navbar" type="submit">-->
<!--            <i class="fas fa-search"></i>-->
<!--          </button>-->
<!--        </div>-->
<!--      </div>-->
<!--    </form>-->

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <span>
         <i class="fas fa-user"></i> {{ user.first_name }} {{ user.last_name }} |
        </span>
        <a href="{% url 'accounts:logout' %}" class="btn">
         <i class="fas fa-sign-out-alt mr-2"></i>Sair</a>
      </li>
    </ul>
  </nav>

apps/theme/templates/theme/partials/sidebar.html
{% load static %}

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
<!--        &lt;!&ndash; Brand Logo &ndash;&gt;-->
<!--        <a href="index3.html" class="brand-link">-->
<!--            <img src="{% static 'img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"-->
<!--                 style="opacity: .8">-->
<!--            <span class="brand-text font-weight-light">Logomarca</span>-->
<!--        </a>-->

        <!-- Sidebar -->
        <div class="sidebar bg-ligth">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item">
                        <a href="{% url 'accounts:dashboard' %}" class="nav-link">
                            <i class="nav-icon fas fa-home"></i>
                            <p>
                                Área De Trabalho
                            </p>
                        </a>
                    </li>

                     <li class="nav-item">
                        <a href="{% url 'customers:customers_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                Clientes
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'attendances:list' %}" class="nav-link">
                            <i class="nav-icon fas fa-address-book"></i>
                            <p>
                                Agenda
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'contacts:contact_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-address-card"></i>
                            <p>
                                Contatos
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-balance-scale"></i>
                            <p>
                                Processos E Casos
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-money-check-alt"></i>
                            <p>
                                Financeiro
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-file-alt"></i>
                            <p>
                                Documentos
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                Alertas
                                <span class="right badge badge-danger"> 5 Novos</span>
                            </p>
                        </a>
                    </li>

                </ul>
            </nav>
        </div>
    </aside>