admin-adv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('customers/', include('apps.customers.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path('attendances/', include('apps.attendances.urls')),
]

apps/customers/urls.py
from django.urls import path
from apps.customers import views

app_name = 'customers'

urlpatterns = [
    path('customers-list/', views.CustomersList.as_view(), name='customers_list'),
    path('customers-create/', views.CustomerCreate.as_view(), name='customers_create'),
    path('customers-detail/<int:pk>', views.CustomerDetail.as_view(), name='customers_detail'),
    path('customers-update/<int:pk>', views.CustomerUpdate.as_view(), name='customers_update'),
]

apps/customers/models.py
from django.db import models
# models
from apps.addresses.models import Address
from apps.contacts.models import Phone


class Customer(models.Model):
    first_name = models.CharField('Primeiro nome', max_length=50)
    full_name = models.CharField('Nome completo', max_length=500)
    birth_date = models.DateField('Data de nascimento')
    cpf = models.CharField('CPF', max_length=20, unique=True)
    rg = models.CharField('RG', max_length=20, unique=True)
    email = models.EmailField('Email', blank=True)
    address = models.ForeignKey(Address, verbose_name='Endereço', on_delete=models.CASCADE)
    phone = models.ForeignKey(Phone, verbose_name='Telefone', on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return self.full_name

apps/customers/forms.py
from django.forms.models import ModelForm
from apps.customers.models import Customer


class CustomerFormCreate(ModelForm):
    class Meta:
        model = Customer
        fields = ('first_name', 'full_name', 'birth_date', 'cpf', 'rg', 'email', 'phone')


class CustomerFormUpdate(ModelForm):
    class Meta:
        model = Customer
        fields = ('full_name', 'rg', 'cpf', 'birth_date')

apps/customers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, TemplateView, UpdateView
from apps.customers.models import Customer
from django.urls import reverse_lazy
from django.shortcuts import redirect
# forms
from apps.customers.forms import CustomerFormCreate, CustomerFormUpdate
from apps.addresses.forms import AddressForm
from apps.contacts.forms import PhoneFormCreate


class CustomersList(LoginRequiredMixin, ListView):
    template_name = 'customers/customers_list.html'
    context_object_name = 'customers'
    model = Customer

    def get_queryset(self):
        queryset = Customer.objects.all()
        search = self.request.GET.get('search', False)
        if search:
            queryset = Customer.objects.filter(
                full_name__icontains=search
            )
        return queryset


class CustomerCreate(LoginRequiredMixin, TemplateView):
    template_name = 'customers/customers_create.html'

    def get_context_data(self, **kwargs):
        context = super(CustomerCreate, self).get_context_data(**kwargs)
        context['form'] = CustomerFormCreate(self.request.POST or None)
        context['form_address'] = AddressForm(self.request.POST or None)
        context['form_phone'] = PhoneFormCreate(self.request.POST or None)
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        customer_form = context['form']
        form_address = context['form_address']
        form_phone = context['form_phone']

        if all((customer_form.is_valid(), form_address.is_valid(), form_phone.is_valid())):
            address = form_address.save()
            customer_form.instance.address = address
            phone = form_phone.save()
            customer_form.instance.phone = phone
            customer = customer_form.save()
            customer.save()
            return redirect(reverse_lazy('customers:customers_list'))
        return self.render_to_response(context)


class CustomerDetail(LoginRequiredMixin, TemplateView):
    template_name = 'customers/customers_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CustomerDetail, self).get_context_data(**kwargs)
        context['customer'] = Customer.objects.filter(
            pk=self.kwargs['pk']
        ).first()
        return context


class CustomerUpdate(UpdateView):
    model = Customer
    form_class = CustomerFormUpdate
    template_name = 'customers/customers_update.html'

    def get_success_url(self):
        return reverse_lazy('customers:customers_detail', kwargs={'pk': self.get_object().pk})

apps/customers/templates/customers/customers_create.html
{% extends 'theme/layouts/base.html' %}

{% block page_title %} Adicionar Clientes {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                {% load widget_tweaks %}
                <form method="post">
                    {% csrf_token %}
                    <h6>
                        <i class="fas fa-address-book mr-2"></i>Informações Básicas
                    </h6>
                    <div class="row">
                        <div class="form-group col-sm-3">
                            <label for="{{ form.first_name.auto_id }}">
                                {{ form.first_name.label }}:
                            </label>
                            {% render_field form.first_name class="form-control" %}
                        </div>
                        <div class="form-group col-sm-6">
                            <label for="{{ form.full_name.auto_id }}">
                                {{ form.full_name.label }}:
                            </label>
                            {% render_field form.full_name class="form-control" %}
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="{{ form.birth_date.auto_id }}">
                                {{ form.birth_date.label }}:
                            </label>
                            {% render_field form.birth_date class="form-control" %}
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="{{ form.cpf.auto_id }}">
                                {{ form.cpf.label }}:
                            </label>
                            {% render_field form.cpf class="form-control" %}
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="{{ form.rg.auto_id }}">
                                {{ form.rg.label }}:
                            </label>
                            {% render_field form.rg class="form-control" %}
                        </div>
                    </div>
                    <h6>
                        <i class="fas fa-map-marker-alt mr-2"></i>Endereço
                    </h6>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="{{ form_address.street.auto_id }}">
                                {{ form_address.street.label }}:
                            </label>
                            {% render_field form_address.street class="form-control" %}
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="{{ form_address.neighborhood.auto_id }}">
                                {{ form_address.neighborhood.label }}:
                            </label>
                            {% render_field form_address.neighborhood class="form-control" %}
                        </div>
                        <div class="form-group col-sm-2">
                            <label for="{{ form_address.number.auto_id }}">
                                {{ form_address.number.label }}:
                            </label>
                            {% render_field form_address.number class="form-control" %}
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="{{ form_address.city.auto_id }}">
                                {{ form_address.city.label }}:
                            </label>
                            {% render_field form_address.city class="form-control" %}
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="{{ form_address.state.auto_id }}">
                                {{ form_address.state.label }}:
                            </label>
                            {% render_field form_address.state class="form-control" %}
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="{{ form_address.complement.auto_id }}">
                                {{ form_address.complement.label }}:
                            </label>
                            {% render_field form_address.complement rows="2" class="form-control" %}
                        </div>
                        <hr>
                    </div>
                    <h6>
                        <i class="fas fa-id-card mr-2"></i>Contato
                    </h6>
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="{{ form.email.auto_id }}">
                                {{ form.email.label }}:
                            </label>
                            {% render_field form.email class="form-control" %}
                        </div>
                        <div class="form-group col-sm-2">
                            <label for="{{ form_phone.ddi.auto_id }}">
                                {{ form_phone.ddi.label }}:
                            </label>
                            {% render_field form_phone.ddi class="form-control" %}
                        </div>
                        <div class="form-group col-sm-2">
                            <label for="{{ form_phone.ddd.auto_id }}">
                                {{ form_phone.ddd.label }}:
                            </label>
                            {% render_field form_phone.ddd class="form-control" %}
                        </div>

                        <div class="form-group col-sm-4">
                            <label for="{{ form_phone.number.auto_id }}">
                                {{ form_phone.number.label }}:
                            </label>
                            {% render_field form_phone.number class="form-control" %}
                        </div>

                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-success">
                                <i class="fas fa-check mr-2"></i> Salvar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/customers/templates/customers/customers_detail.html
{% extends 'theme/layouts/base.html' %}

{% block page_title %} Detalhe De Cliente {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
        <div class="card profile px-2">
            <div class="card-header">
                <h4 class="text-center">{{ customer.first_name }}</h4>
            </div>
            <div class="card-body">

                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <strong>Nome Completo:</strong> {{ customer.full_name }}
                    </li>
                    <li class="list-group-item">
                        <strong>Cpf:</strong> {{ customer.rg }}
                    </li>
                    <li class="list-group-item">
                        <strong>Cpf:</strong> {{ customer.cpf }}
                    </li>
                    <li class="list-group-item">
                        <strong>Data De Nascimento: </strong> {{ customer.birth_date }}
                    </li>
                </ul>

            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-sm-12">
                        <a href="{% url 'customers:customers_update' customer.pk %}" class="btn btn-secondary float-right">
                            <i class="fas fa-edit mr-2"></i>Editar
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- list address   -->
    <div class="col-sm-8">
        <div class="row">
            <!--    table address        -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-12 d-flex justify-content-between">
                                <h5>Endereços:</h5>
                                <a href="#" class="btn btn-success btn-sm">
                                    <i class="fas fa-plus mr-2"></i>Adicioar Endereço
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <th>Rua</th>
                                <th>Número</th>
                                <th>Bairro</th>
                                <th>Cidade</th>
                                <th>Ações</th>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-12 d-flex justify-content-between">
                                <h5>Contatos:</h5>
                                <a href="#" class="btn btn-success btn-sm">
                                    <i class="fas fa-plus mr-2"></i>Adicioar Contato
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <th>Email</th>
                                <th>Telefone</th>
                                <th>Bairro</th>
                                <th>Ações</th>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/customers/templates/customers/customers_list.html
{% extends 'theme/layouts/base.html' %}

{% block page_title %} Lista De Clientes {% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm-12">
        <div class="card px-2 py-4">
            <div class="card-header">
                <form method="get">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="input-group">
                                <button class="btn btn-light">
                                    <i class="fas fa-search"></i>
                                </button>
                                <input class="form-control" type="text" placeholder="Pesquisar por nome" name="search">
                            </div>
                        </div>
                        <div class="form-group col-sm-8">
                            <a href="{% url 'customers:customers_create' %}" class="btn btn-success float-right">
                                Adicionar
                                <i class="fas fa-plus ml-2"></i>
                            </a>
                            <a href="{% url 'customers:customers_list' %}" class="btn btn-secondary">
                                Limpar Filtros
                                <i class="fas fa-broom ml-2"></i>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Cpf</th>
                        <th>Rg</th>
                        <th>Data De Nascimento</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in customers %}
                    <tr>
                        <td><a href="{% url 'customers:customers_detail' customer.pk %}">{{ customer.full_name }}</a></td>
                        <td>{{ customer.cpf }}</td>
                        <td>{{ customer.rg }}</td>
                        <td>{{ customer.birth_date }}</td>
                        <td>
                            <a href="{% url 'customers:customers_update' customer.pk %}" class="btn btn-primary btn-sm py-2">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="#" title="Excluir" class="btn btn-danger btn-sm py-2">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <td class="text-center" colspan="5">
                        Nenhum Cliente Encontrado
                    </td>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/customers/templates/customers/customers_update.html
{% extends 'theme/layouts/base.html' %}

{% block page_title %} Editar Cliente {% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="{{ form.full_name.auto_id }}">
                                {{ form.full_name.label }}:
                            </label>
                            {% render_field form.full_name class="form-control" %}
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="{{ form.full_name.auto_id }}">
                                {{ form.rg.label }}:
                            </label>
                            {% render_field form.rg class="form-control" %}
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="{{ form.full_name.auto_id }}">
                                {{ form.cpf.label }}:
                            </label>
                            {% render_field form.cpf class="form-control" %}
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="{{ form.birth_date.auto_id }}">
                                {{ form.birth_date.label }}:
                            </label>
                            {% render_field form.birth_date class="form-control" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-success mr-2">
                                <i class="fas fa-check mr-2"></i>Salvar
                            </button>
                            <a class="btn btn-secondary" href="{% url 'customers:customers_list' %}">
                                <i class="fas fa-window-close mr-2"></i>Cancelar
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}